# Generated by Django 3.1.6 on 2021-10-19 10:09
# Altered to fix problem after deleting "datalake" application.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20211019_0541'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='DatalakeConnection',
        # ),
    ]
